### ISSUE TITLE
terway CrashLoopBackOff:  felix panic: Failed to execute ip(6)tables-restore command error=exit status 1 errorOutput="ip6tables-nft-restore v1.8.8 (nf_tables): Can't open socket to ipset

### ISSUE THREAD

**Issue by cyclinder** [AliyunContainerService/terway#524]
仓库提供的 terway-multiip.yaml 可能需要修改下，不然policy 因权限不足无法 list servces等资源。 

```shell
2023-08-24 15:52:25.094 [INFO][86264] felix/watchercache.go 194: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesservice" error=connection is unauthorized: services is forbidden: User "system:serviceaccount:kube-system:terway" cannot list resource "services" in API group "" at the cluster scope
2023-08-24 15:52:26.093 [INFO][86264] felix/watchercache.go 194: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=connection is unauthorized: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:kube-system:terway" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
```

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terway-pod-reader
  namespace: kube-system
rules:
  - apiGroups: [ "" ]
+  resources: [ "services","pods", "nodes", "namespaces", "configmaps", "serviceaccounts" ]
-   resources: ["pods", "nodes", "namespaces", "configmaps", "serviceaccounts" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources:
      - events
    verbs:
      - create
  - apiGroups: [ "networking.k8s.io" ]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "crd.projectcalico.org" ]
    resources: [ "*" ]
    verbs: [ "*" ]
+ - apiGroups: [ "discovery.k8s.io" ]
+   resources:
+   - endpointslices
+   verbs:
+    - get
+    - list
+    - watch
...
```

补齐上述权限之后，terway pod直接挂了，报错执行ip6tables命令失败：

```shell
[root@iZ2vc5zub002vrlwursb4rZ cyclinder]# kk get po
NAME                                                        READY   STATUS             RESTARTS       AGE
coredns-56bd89c8d6-tjmzn                                    0/1     CrashLoopBackOff   13 (13s ago)   46m
coredns-56bd89c8d6-ztkn2                                    0/1     CrashLoopBackOff   13 (33s ago)   46m
etcd-cn-chengdu.i-2vc5zub002vrlwursb4r                      1/1     Running            3              100m
kube-apiserver-cn-chengdu.i-2vc5zub002vrlwursb4r            1/1     Running            1              100m
kube-controller-manager-cn-chengdu.i-2vc5zub002vrlwursb4r   1/1     Running            0              100m
kube-proxy-8ktfw                                            1/1     Running            1              58m
kube-proxy-stkgg                                            1/1     Running            0              99m
kube-scheduler-cn-chengdu.i-2vc5zub002vrlwursb4r            1/1     Running            7              100m
terway-8vtlb                                                1/2     CrashLoopBackOff   6 (44s ago)    47m
terway-tm2nx                                                1/2     CrashLoopBackOff   6 (39s ago)    47m
```

```shell
2023-08-24 16:00:14.655 [WARNING][90276] felix/table.go 1002: Retrying... error=exit status 1 ipVersion=0x4 table="nat"
2023-08-24 16:00:14.659 [WARNING][90276] felix/table.go 1321: Failed to execute ip(6)tables-restore command error=exit status 1 errorOutput="iptables-nft-restore v1.8.8 (nf_tables): Can't open socket to ipset.\n\n" input="*nat\n:cali-fip-dnat - -\n:cali-fip-snat - -\n:cali-nat-outgoing - -\n:cali-PREROUTING - -\n:cali-POSTROUTING - -\n:cali-OUTPUT - -\n-A cali-POSTROUTING -m comment --comment \"cali:Z-c7XtVd2Bq7s_hA\" --jump cali-fip-snat\n-A cali-POSTROUTING -m comment --comment \"cali:nYKhEzDlr11Jccal\" --jump cali-nat-outgoing\n-A cali-OUTPUT -m comment --comment \"cali:GBTAv2p5CwevEyJm\" --jump cali-fip-dnat\n-A cali-nat-outgoing -m comment --comment \"cali:flqWnvo8yq4ULQLa\" -m set --match-set cali40masq-ipam-pools src -m set ! --match-set cali40all-ipam-pools dst --jump MASQUERADE --random-fully\n-A cali-PREROUTING -m comment --comment \"cali:r6XmIziWUJsdOK6Z\" --jump cali-fip-dnat\n-I PREROUTING -m comment --comment \"cali:6gwbT8clXdHdC1b1\" --jump cali-PREROUTING\n-I OUTPUT -m comment --comment \"cali:tVnHkvAo15HuiPy0\" --jump cali-OUTPUT\n-I POSTROUTING -m comment --comment \"cali:O3lYWMrLQYEMJtB5\" --jump cali-POSTROUTING\nCOMMIT\n" ipVersion=0x4 output="" table="nat"
2023-08-24 16:00:14.659 [WARNING][90276] felix/table.go 999: Failed to program iptables, will retry error=exit status 1 ipVersion=0x4 table="nat"
2023-08-24 16:00:15.165 [WARNING][90276] felix/table.go 1002: Retrying... error=exit status 1 ipVersion=0x6 table="nat"
2023-08-24 16:00:15.170 [WARNING][90276] felix/table.go 1321: Failed to execute ip(6)tables-restore command error=exit status 1 errorOutput="ip6tables-nft-restore v1.8.8 (nf_tables): Can't open socket to ipset.\n\n" input="*nat\n:cali-fip-dnat - -\n:cali-fip-snat - -\n:cali-nat-outgoing - -\n:cali-PREROUTING - -\n:cali-POSTROUTING - -\n:cali-OUTPUT - -\n-A cali-OUTPUT -m comment --comment \"cali:GBTAv2p5CwevEyJm\" --jump cali-fip-dnat\n-A cali-nat-outgoing -m comment --comment \"cali:Ir_z2t1P6-CxTDof\" -m set --match-set cali60masq-ipam-pools src -m set ! --match-set cali60all-ipam-pools dst --jump MASQUERADE --random-fully\n-A cali-PREROUTING -m comment --comment \"cali:r6XmIziWUJsdOK6Z\" --jump cali-fip-dnat\n-A cali-POSTROUTING -m comment --comment \"cali:Z-c7XtVd2Bq7s_hA\" --jump cali-fip-snat\n-A cali-POSTROUTING -m comment --comment \"cali:nYKhEzDlr11Jccal\" --jump cali-nat-outgoing\n-I PREROUTING -m comment --comment \"cali:6gwbT8clXdHdC1b1\" --jump cali-PREROUTING\n-I OUTPUT -m comment --comment \"cali:tVnHkvAo15HuiPy0\" --jump cali-OUTPUT\n-I POSTROUTING -m comment --comment \"cali:O3lYWMrLQYEMJtB5\" --jump cali-POSTROUTING\nCOMMIT\n" ipVersion=0x6 output="" table="nat"
2023-08-24 16:00:15.170 [ERROR][90276] felix/table.go 1006: Failed to program iptables, loading diags before panic. error=exit status 1 ipVersion=0x6 table="nat"
2023-08-24 16:00:15.171 [WARNING][90276] felix/table.go 1002: Retrying... error=exit status 1 ipVersion=0x4 table="nat"
2023-08-24 16:00:15.173 [ERROR][90276] felix/table.go 1012: Current state of iptables ipVersion=0x6 iptablesState="# Generated by ip6tables-nft-save v1.8.8 (nf_tables) on Thu Aug 24 16:00:15 2023\n*nat\n:PREROUTING ACCEPT [0:0]\n:INPUT ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:POSTROUTING ACCEPT [0:0]\n:KUBE-KUBELET-CANARY - [0:0]\n:KUBE-MARK-MASQ - [0:0]\n:KUBE-NODEPORTS - [0:0]\n:KUBE-POSTROUTING - [0:0]\n:KUBE-PROXY-CANARY - [0:0]\n:KUBE-SERVICES - [0:0]\n-A PREROUTING -m comment --comment \"kubernetes service portals\" -j KUBE-SERVICES\n-A OUTPUT -m comment --comment \"kubernetes service portals\" -j KUBE-SERVICES\n-A POSTROUTING -m comment --comment \"kubernetes postrouting rules\" -j KUBE-POSTROUTING\n-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000\n-A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN\n-A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0\n-A KUBE-POSTROUTING -m comment --comment \"kubernetes service traffic requiring SNAT\" -j MASQUERADE --random-fully\n-A KUBE-SERVICES ! -d ::1/128 -m comment --comment \"kubernetes service nodeports; NOTE: this must be the last rule in this chain\" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS\nCOMMIT\n# Completed on Thu Aug 24 16:00:15 2023\n" table="nat"
2023-08-24 16:00:15.173 [PANIC][90276] felix/table.go 1014: Failed to program iptables, giving up after retries error=exit status 1 ipVersion=0x6 table="nat"
panic: (*logrus.Entry) 0xc0003aa2a0

goroutine 229 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0003aa230, 0x0, {0xc0005f4500, 0x33})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x47e
github.com/sirupsen/logrus.(*Entry).Log(0xc0003aa230, 0x0, {0xc0005f1620?, 0x5?, 0x40613d9c?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/projectcalico/calico/felix/iptables.(*Table).Apply(0xc0002a7800)
        /go/src/github.com/projectcalico/calico/felix/iptables/table.go:1014 +0xbc5
github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).apply.func4(0xc0007a0f00?)
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:2034 +0x52
created by github.com/projectcalico/calico/felix/dataplane/linux.(*InternalDataplane).apply
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:2033 +0x717
```

**Comment by l1b0k** [comment]
Thanks for reporting, #536 should have fixed
